In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [4]:
df_tran = gpd.read_file('./data/raw_data/transportation.geojson')

In [5]:
df_tran.head()

,subclass,footway,crossing,curbramps,length,description,incline,surface,width,layer,elevator,indoor,opening_hours,geometry
0,footway,crossing,unmarked,1.0,21.13,Crossing at 1ST AVE,NaN,None,NaN,NaN,NaN,NaN,None,"LINESTRING (-122.33431401 47.60182781, -122.33..."
1,footway,crossing,marked,1.0,20.46,Crossing at 1ST AVE S,NaN,None,NaN,NaN,NaN,NaN,None,"LINESTRING (-122.33404306 47.60163572, -122.33..."
2,footway,crossing,marked,1.0,20.09,Crossing at YESLER WAY,NaN,None,NaN,NaN,NaN,NaN,None,"LINESTRING (-122.3343147 47.60164708, -122.334..."
3,footway,crossing,marked,1.0,15.85,Crossing at YESLER WAY,NaN,None,NaN,NaN,NaN,NaN,None,"LINESTRING (-122.33404254 47.60177833, -122.33..."
4,footway,crossing,marked,1.0,20.40,Crossing at 1ST AVE,NaN,None,NaN,NaN,NaN,NaN,None,"LINESTRING (-122.33410269 47.60253483, -122.33..."

In [7]:
df_crossing.head()

,Unnamed: 0,ID,curbramps,length,description,incline,surface,width,layer,elevator,indoor,opening_hours,v_coordinates,u_coordinates
0,0,1,1,21.13,Crossing at 1ST AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(-122.33431401,47.60182781)","(-122.33404254,47.60177833)"
1,1,2,1,20.46,Crossing at 1ST AVE S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(-122.33404306,47.60163572)","(-122.3343147,47.60164708)"
2,2,3,1,20.09,Crossing at YESLER WAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(-122.3343147,47.60164708)","(-122.33431401,47.60182781)"
3,3,4,1,15.85,Crossing at YESLER WAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(-122.33404254,47.60177833)","(-122.33404306,47.60163572)"
4,4,5,1,20.40,Crossing at 1ST AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(-122.33410269,47.60253483)","(-122.33433443,47.60243928)"