In [21]:
import geopandas as gpd
import pandas as pd

In [13]:
dir1 = 'C:\\Users\\xiegudong45\\Desktop\\CSE495\\City-scale-Analytics\\Shenghao\\data\\park_only_boundary1.geojson'
dir2 = 'C:\\Users\\xiegudong45\\Desktop\\CSE495\\City-scale-Analytics\\Shenghao\\data\\sidewalk_trail.geojson'
st_df = gpd.read_file(dir2)
pb_df = gpd.read_file(dir1)

In [24]:
st_df.head()

,condition,forward,graph_layer,incline,layer,length,pkey,side,street_name,streets_pkey,...,width,amwoid,grade_perc,grade_type,pma_name,pmaid,trail_clas,trail_id,type,geometry
0,FAIR,1.0,sidewalk,-15.0,0.0,28.55368477083827,314716.0,N,S BENNETT ST,19496.0,...,1.524,None,None,None,None,None,None,None,None,LINESTRING (-122.3109895837122 47.554803238548...
1,FAIR,1.0,sidewalk,0.0,0.0,6.256332034174294,314716.0,N,S BENNETT ST,19496.0,...,1.524,None,None,None,None,None,None,None,None,LINESTRING (-122.3110727362415 47.554803619255...
2,GOOD,0.0,sidewalk,-40.0,0.0,67.39927884547073,307254.0,E,8TH AVE NE,8328.0,...,1.8288,None,None,None,None,None,None,None,None,LINESTRING (-122.3202017666824 47.688878742907...
3,GOOD,1.0,sidewalk,-90.0,0.0,129.6843287406617,326146.0,S,SW STEVENS ST,22859.0,...,1.8288,None,None,None,None,None,None,None,None,LINESTRING (-122.3980609246822 47.577509031485...
4,GOOD,1.0,sidewalk,-191.0,0.0,86.02870971671874,312705.0,NE,E TERRACE ST,14841.0,...,1.8288,None,None,None,None,None,None,None,None,LINESTRING (-122.2845035229847 47.605122629780...

In [15]:
pb_df.head(2)

,name,shape_area,parksbnd_a,pma,shape_len,geometry
0,12TH AVE SQUARE PARK,0,7316.172948,4467,0,(POLYGON ((-122.3162480182179 47.6071438821052...
1,6TH AVENUE NW POCKET PARK,0,9006.612569,3158,0,(POLYGON ((-122.3634527097912 47.6843669164890...

In [18]:
pb_df.drop(['shape_area', 'shape_len'], axis=1, inplace=True)
pb_df.rename(columns={'parksbnd_a': 'park_area'}, inplace=True)
pb_df['graph_layer'] = 'park_boundary'
pb_df.head(2)

,name,park_area,pma,geometry,graph_layer
0,12TH AVE SQUARE PARK,7316.172948,4467,(POLYGON ((-122.3162480182179 47.6071438821052...,park_boundary
1,6TH AVENUE NW POCKET PARK,9006.612569,3158,(POLYGON ((-122.3634527097912 47.6843669164890...,park_boundary

In [23]:
combine_df = pd.concat([pb_df, st_df], ignore_index=True)
combine_df.head()

C:\Users\xiegudong45\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

,amwoid,condition,forward,geometry,grade_perc,grade_type,graph_layer,incline,layer,length,...,pma_name,pmaid,side,street_name,streets_pkey,surface,trail_clas,trail_id,type,width
0,NaN,NaN,NaN,(POLYGON ((-122.3162480182179 47.6071438821052...,NaN,NaN,park_boundary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,(POLYGON ((-122.3634527097912 47.6843669164890...,NaN,NaN,park_boundary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,(POLYGON ((-122.348654185465 47.65023051082457...,NaN,NaN,park_boundary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,(POLYGON ((-122.2984079350166 47.7206142912442...,NaN,NaN,park_boundary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,(POLYGON ((-122.3715039366772 47.7123967271094...,NaN,NaN,park_boundary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
combine_df.to_file('C:\\Users\\xiegudong45\\Desktop\\CSE495\\City-scale-Analytics\\Shenghao\\data\\sidewalk_trail_boundary.geojson', driver='GeoJSON')

ValueError: Geometry column cannot contain mutiple geometry types when writing to file.